drake/urls.py
from django.urls import path
from . import views

app_name = 'drake'

urlpatterns = [
    path("explore/", views.search_drake, name='search_drake'),
    path(f"word-cloud/<str:encoded_album>", views.get_album_cloud, name='get_album_cloud'),
    path("all-projects-cloud/", views.get_projects_cloud, name='get_projects_cloud')
]

foodOfLove/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "home"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name='home'),
    path("tinashe/", include('nashe.urls')),
    path("drake/", include('drake.urls')),

]

nashe/urls.py
from django.urls import path
from . import views

app_name = 'nashe'

urlpatterns = [
    path("explore/", views.nashe_albums, name='nashe_albums'),
    path(f"word-cloud/<str:encoded_album>", views.get_album_cloud, name='get_album_cloud'),
    path("all-projects-cloud/All-Projects", views.get_projects_cloud, name='get_projects_cloud')
]

nashe/models.py
from django.db import models

# Create your models here.

nashe/views.py
from django.shortcuts import render
from io import BytesIO
import base64
import os
from .functions import *
from urllib.parse import unquote


# Create your views here.
def nashe_albums(request):
    return render(request, "nashe/explore_tinashe.html")


def get_projects_cloud(request):
    banner_path = os.path.join('static', 'images', 'albums', 'nashe', '7.png')

    with open(banner_path, 'rb') as image_file:
        banner = base64.b64encode(image_file.read()).decode("utf-8")

    album = 'All Projects'

    # get selected album's lyrics
    proj_Lyrics = get_project_lyrics()

    # clean up lyrics
    clean_lyrics = process_lyrics(proj_Lyrics)

    # get word count
    word_count = check_frequency(clean_lyrics)

    # create word cloud
    word_cloud = create_word_cloud(word_count)

    # Convert the word cloud image to bytes
    image_stream = BytesIO()
    word_cloud.to_image().save(image_stream, format="PNG")  # Save as PNG format (or the desired format)
    image_stream.seek(0)
    encoded_image = base64.b64encode(image_stream.read()).decode("utf-8")

    context = {
        'word_cloud': encoded_image,
        'banner': banner,
        'album': album
    }

    return render(request, 'nashe/word_cloud.html', context=context)


# getting word cloud for singular album
def get_album_cloud(request, encoded_album):
    # Decode the album name from the URL
    album = unquote(encoded_album)

    if album == "Songs For You":
        banner_path = os.path.join('static', 'images', 'albums', 'nashe', '10.png')

        with open(banner_path, 'rb') as image_file:
            banner = base64.b64encode(image_file.read()).decode("utf-8")

    elif album == '333':
        banner_path = os.path.join('static', 'images', 'albums', 'nashe', '9.png')

        with open(banner_path, 'rb') as image_file:
            banner = base64.b64encode(image_file.read()).decode("utf-8")

    elif album == 'BBANG3L':
        banner_path = os.path.join('static', 'images', 'albums', 'nashe', '8.png')

        with open(banner_path, 'rb') as image_file:
            banner = base64.b64encode(image_file.read()).decode("utf-8")

    else:
        banner_path = os.path.join('static', 'images', 'albums', 'nashe', '7.png')

        with open(banner_path, 'rb') as image_file:
            banner = base64.b64encode(image_file.read()).decode("utf-8")

    # get selected album's lyrics
    album_Lyrics = get_album_lyrics(album)

    # clean up lyrics
    clean_lyrics = process_lyrics(album_Lyrics)

    # get word count
    word_count = check_frequency(clean_lyrics)

    # create word cloud
    word_cloud = create_word_cloud(word_count)

    # Convert the word cloud image to bytes
    image_stream = BytesIO()
    word_cloud.to_image().save(image_stream, format="PNG")  # Save as PNG format (or the desired format)
    image_stream.seek(0)
    encoded_image = base64.b64encode(image_stream.read()).decode("utf-8")

    context = {
        'word_cloud': encoded_image,
        'album': album,
        'banner': banner
    }

    return render(request, 'nashe/word_cloud.html', context=context)

templates/nashe/explore_tinashe.html
{% extends 'base.html' %}
{% load static%}
{% block title %}
Tinashe
{% endblock %}

{% block content %}
<h3> Tinashe </h3>
<section>
      <div class="container">
          <div class="row content">
            <div class="col-lg-6" data-aos="fade-right">
            <img src="{% static 'images/nashe.jpeg' %}" class="rounded-circle" width="400" height="300">
          </div>
          </div>
          <hr>
        <h2>Select An Album to Analyse</h2>
        <div class="row">
          <div class="col-sm-4">
            <a href="{% url 'nashe:get_album_cloud' encoded_album='Songs%20For%20You' %}">
              <img src="{% static 'images/albums/nashe/SFY.jpeg' %}" class="img-fluid">
            </a>
            <figcaption><strong>Songs For You</strong></figcaption>
          </div>
            <div class="col-sm-4">
            <a href="{% url 'nashe:get_album_cloud' encoded_album='333' %}">
              <img src="{% static 'images/albums/nashe/333.jpeg' %}" class="img-fluid">
            </a>
            <figcaption><strong>333</strong></figcaption>
          </div>
            <div class="col-sm-4">
            <a href="{% url 'nashe:get_album_cloud' encoded_album='BBANG3L' %}">
              <img src="{% static 'images/albums/nashe/BB:Ang3l.jpeg' %}" class="img-fluid">
            </a>
            <figcaption><strong>BB/Ang3l</strong></figcaption>
          </div>
        </div>
          <br><br>
           <a class="btn btn-primary btn-lg" href="{% url 'nashe:get_projects_cloud' %}" role="button">Analyse All Projects</a>
    </div>
    </section>
{% endblock %}

templates/nashe/word_cloud.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ album }} Cloud
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <img class="d-block w-100" src="data:image/png;base64,{{ banner }}" alt="Album Banner">
    </div>
    <hr>
    <h1 class="text-center">{{ album }}'s Word Cloud</h1>
    <br>
    <div class="text-center">  <!-- Center-align the word cloud -->
        <img src="data:image/png;base64,{{ word_cloud }}" alt="Word Cloud" style="max-width: 100%; height: auto;">  <!-- Set max-width and auto height for responsiveness -->
    </div>
{% endblock %}