drake/urls.py
from django.urls import path
from . import views

app_name = 'drake'

urlpatterns = [
    path("explore/", views.search_drake, name='search_drake'),
    path(f"word-cloud/<str:encoded_album>", views.get_album_cloud, name='get_album_cloud'),
    path("all-projects-cloud/", views.get_projects_cloud, name='get_projects_cloud')
]

foodOfLove/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "home"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name='home'),
    path("tinashe/", include('nashe.urls')),
    path("drake/", include('drake.urls')),

]

nashe/urls.py
from django.urls import path
from . import views

app_name = 'nashe'

urlpatterns = [
    path("explore/", views.nashe_albums, name='nashe_albums'),
    path(f"word-cloud/<str:encoded_album>", views.get_album_cloud, name='get_album_cloud'),
    path("all-projects-cloud/All-Projects", views.get_projects_cloud, name='get_projects_cloud')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bootstrap Page</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
</head>
<body class="container">
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light  bg-white">
        <a class="navbar-brand" href="{% url 'home' %}">Food Of Love</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'nashe:nashe_albums' %}">Tinashe</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'drake:search_drake' %}">Drake</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <br><br><br>
    <footer class="footer mt-auto py-3 bg-light bg-white">
    <div class="container text-center">
        <p>Developed By Kudzayi Bamhare 2023. &copy; Food Of Love. All rights reserved.</p>
    </div>
</footer>

    <!-- Include Bootstrap JS and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static%}
{% block title %}
Home
{% endblock %}

{% block content %}

    <!-- Banner Image -->
    <div class="jumbotron">
        <img class="d-block w-100" src="{% static 'images/f-banner.png' %}">
        <hr class="my-4">
         <h3 class="display-4"><i>If music feeds our desire to love, then play on, musician. <br><br>Play so much music that I become
             stuffed with it, so love’s appetite for hearing music grows sick and dies.</i></h3>
    </div>

    <!-- Container with Two Images and Text Below -->
    <div class="container mt-5">
        <p>Explore visualizations that highlight the most frequently used words and phrases in Drake's and Tinashe's lyrics.
            Gain insights into their lyrical themes and what your favourite albums are really about.</p>
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'images/drake.jpeg' %}" class="img-fluid equal-size" alt="Image 1">
                <p class="mt-2">Description of Image 1</p>
                <a class="btn btn-primary btn-lg" href="{% url 'drake:search_drake' %}" role="button">Explore Drake</a>
            </div>
            <div class="col-md-6">
                <img src="{% static 'images/nashe.jpeg' %}" class="img-fluid equal-size" alt="Image 2">
                <p class="mt-2">Description of Image 2</p>
                <a class="btn btn-primary btn-lg" href="{% url 'nashe:nashe_albums' %}" role="button">Explore Tinashe</a>
            </div>
        </div>
    </div>
{% endblock %}